name: webapp_aruna
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

    
  responsive_framework: ^0.2.0
  google_fonts: ^2.3.2
  animations: ^2.0.2
  loading_gifs: ^0.3.0
  dio: ^4.0.6
  shimmer: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

